const CssStyles = {
  FormLogin: {
    width: "300px",
    padding: "10px 25px",
    backgroundColor: "rgb(111, 199, 107)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "16px",
    boxShadow: "0px 0px 5px rgba(0,0,0,0.3)",
    transition: "background-color 0.2s ease-in-out",
    textDecoration: "none",
    display: "inline-block",
    marginRight: "10px",
    marginLeft: "10px",
    marginTop: "10px",
    marginBottom: "10px",
  },
  FormRegister: {
    width: "300px",
    padding: "10px 25px",
    backgroundColor: "rgb(107, 185, 199)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "16px",
    boxShadow: "0px 0px 5px rgba(0,0,0,0.3)",
    transition: "background-color 0.2s ease-in-out",
    textDecoration: "none",
    display: "inline-block",
    marginRight: "10px",
    marginLeft: "10px",
    marginTop: "10px",
    marginBottom: "10px",
  },
  buttonStyles: {
    width: "100px",
    padding: "10px 25px",
    backgroundColor: "rgb(111, 199, 107)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "16px",
    boxShadow: "0px 0px 5px rgba(0,0,0,0.3)",
    transition: "background-color 0.2s ease-in-out",
    textDecoration: "none",
    display: "inline-block",
    marginRight: "10px",
    marginLeft: "10px",
    marginTop: "10px",
    marginBottom: "10px",
  },
};
export default CssStyles;
